apiVersion: apps/v1
kind: Deployment
metadata:
  name: auditing-api
  labels:
    app: auditing-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auditing-api
  template:
    metadata:
      labels:
        app: auditing-api
    spec:
      containers:
        - name: auditing-api
          image: gyliana/auditing-api:latest
          ports:
            - containerPort: 80
          env:
            - name: ConnectionStrings__DefaultConnection
              value: "Server=audit-sqlserver;Database=Logs;User=sa;Password=YourStrong!Password;Persist Security Info=False;Encrypt=False"
            - name: RabbitMQ__Host
              value: "rabbitmq"
            - name: RabbitMQ__User
              value: "guest"
            - name: RabbitMQ__Pass
              value: "guest"
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: ASPNETCORE_URLS
              value: "http://+:80"

          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi