apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-saver
  labels:
    app: log-saver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-saver
  template:
    metadata:
      labels:
        app: log-saver
    spec:
      containers:
        - name: log-saver
          image: gyliana/log-saver:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: secret-volume
              mountPath: /secrets
              readOnly: true
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi
      volumes:
        - name: secret-volume
          secret:
            secretName: log-saver-secrets
