apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-api
  labels:
    app: user-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-api
  template:
    metadata:
      labels:
        app: user-api
    spec:
      containers:
        - name: user-api
          image: gyliana/user-api:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          env:
            - name: ConnectionStrings__DefaultConnection
              value: "Server=user-sqlserver;Database=UserDb;User=sa;Password=YourStrong!Password;Persist Security Info=False;Encrypt=False"
            - name: RabbitMQ__Host
              value: "rabbitmq"
            - name: RabbitMQ__User
              value: "guest"
            - name: RabbitMQ__Pass
              value: "guest"
            - name: JWT__Key
              value: "SuperSecretDebugKeyForTesting12345"
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"