apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-api
  labels:
    app: user-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-api
  template:
    metadata:
      labels:
        app: user-api
    spec:
      containers:
        - name: user-api
          image: gyliana/user-api:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: secret-volume
              mountPath: "/Secrets"
              readOnly: true
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
      volumes:
        - name: secret-volume
          secret:
            secretName: user-secrets
