name: API Gateway CI/CD

on:
  push:
    paths:
      - 'ApiGateway/**'
      - '.github/workflows/api-gateway.yml'
  pull_request:
    paths:
      - 'ApiGateway/**'
      - '.github/workflows/api-gateway.yml'

jobs:
  setup:
    uses: ./.github/workflows/setup/setup-dotnet.yml
    with:
      dotnet_version: '8.0'

  lint:
    uses: ./.github/workflows/setup/lint.yml
    needs: setup
    with:
      solution_path: DocumentManagementSystem.sln

  format:
    uses: ./.github/workflows/setup/format-check.yml
    needs: setup
    with:
      solution_path: DocumentManagementSystem.sln

  build:
    runs-on: ubuntu-latest
    needs: [lint, format]
    steps:
      - uses: actions/checkout@v4
      - run: |
          cd ApiGateway
          dotnet restore
          dotnet build --configuration Release

  docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - run: docker build -t gyliana/api-gateway:${{ github.sha }} -f ApiGateway/Dockerfile .
      - run: docker push gyliana/api-gateway:${{ github.sha }}
      - run: docker tag gyliana/api-gateway:${{ github.sha }} gyliana/api-gateway:latest
      - run: docker push gyliana/api-gateway:latest
