apiVersion: v1
kind: Service
metadata:
  name: accesscontrol-api
  labels:
    app: accesscontrol-api
spec:
  selector:
    app: accesscontrol-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP