apiVersion: v1
kind: Service
metadata:
  name: document-api
  labels:
    app: document-api
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: document-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
