apiVersion: v1
kind: Service
metadata:
  name: log-saver
  labels:
    app: log-saver
spec:
  selector:
    app: log-saver
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
