name: Access Control API CD

on:
  push:
    paths:
      - 'Access_Control/**'
      - '.github/workflows/access-control-cd.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Docker login
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Pull latest Access Control API image
        run: docker pull gyliana/access-control-api:latest

      - name: Update Kubernetes deployment
        run: |
          kubectl set image deployment/access-control-api access-control-api=gyliana/access-control-api:latest
          kubectl rollout status deployment/access-control-api
