name: Access Control API CI

on:
  push:
    paths:
      - 'Access_Control/**'
      - '.github/workflows/access-control.yml'
  pull_request:
    paths:
      - 'Access_Control/**'
      - '.github/workflows/access-control.yml'

jobs:
  setup:
    uses: ./.github/workflows/setup-dotnet.yml
    with:
      dotnet_version: '8.0'

  lint:
    uses: ./.github/workflows/lint.yml
    needs: setup
    with:
      solution_path: DocumentManagementSystem.sln

  format:
    uses: ./.github/workflows/format-check.yml
    needs: setup
    with:
      solution_path: DocumentManagementSystem.sln

  secrets:
    uses: ./.github/workflows/gitguardian.yml
    secrets:
      GG_SHIELD_API_KEY: ${{ secrets.GG_SHIELD_API_KEY }}
    with:
      base_branch: 'origin/main'

  build:
    runs-on: ubuntu-latest
    needs: [lint, format]
    steps:
      - uses: actions/checkout@v4
      - run: |
          cd Access_Control/AccessControl.Api
          dotnet restore
          dotnet build --configuration Release

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - run: dotnet restore Access_Control/AccessControl.Api.Test/AccessControl.Api.Test.csproj
      - run: |
          cd Access_Control/AccessControl.Api.Test
          dotnet test --configuration Release
      - uses: actions/upload-artifact@v4
        with:
          name: access-control-api-test-results
          path: Access_Control/AccessControl.Api.Test/TestResults

  docker:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - run: docker build -t gyliana/access-control-api:${{ github.sha }} -f Access_Control/AccessControl.Api/Dockerfile .
      - run: docker push gyliana/access-control-api:${{ github.sha }}
      - run: docker tag gyliana/access-control-api:${{ github.sha }} gyliana/access-control-api:latest
      - run: docker push gyliana/access-control-api:latest

  snyk:
    uses: ./.github/workflows/snyk.yml
    needs: test
    with:
      solution_path: DocumentManagementSystem.sln
    secrets:
      snyk_token: ${{ secrets.SNYK_TOKEN }}
