name: Auditing API CD

on:
  push:
    paths:
      - 'Auditing/**'
      - '.github/workflows/auditing-cd.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Docker login
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Pull latest Auditing API image
        run: docker pull gyliana/auditing-api:latest

      - name: Update Kubernetes deployment
        run: |
          kubectl set image deployment/auditing-api auditing-api=gyliana/auditing-api:latest
          kubectl rollout status deployment/auditing-api
