name: Auditing API CI/CD

on:
  push:
    paths:
      - 'Auditing/**'
      - '.github/workflows/auditing.yml'
  pull_request:
    paths:
      - 'Auditing/**'
      - '.github/workflows/auditing.yml'

jobs:
  setup:
    uses: ./.github/workflows/setup/setup-dotnet.yml
    with:
      dotnet_version: '8.0'

  lint:
    uses: ./.github/workflows/setup/lint.yml
    needs: setup
    with:
      solution_path: DocumentManagementSystem.sln

  format:
    uses: ./.github/workflows/setup/format-check.yml
    needs: setup
    with:
      solution_path: DocumentManagementSystem.sln

  build:
    runs-on: ubuntu-latest
    needs: [lint, format]
    steps:
      - uses: actions/checkout@v4
      - run: |
          cd Auditing/Auditing.Api
          dotnet restore
          dotnet build --configuration Release

  docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - run: docker build -t gyliana/auditing-api:${{ github.sha }} -f Auditing/Auditing.Api/Dockerfile .
      - run: docker push gyliana/auditing-api:${{ github.sha }}
      - run: docker tag gyliana/auditing-api:${{ github.sha }} gyliana/auditing-api:latest
      - run: docker push gyliana/auditing-api:latest

  snyk:
    uses: ./.github/workflows/analysis/snyk.yml
    needs: build
    with:
      solution_path: DocumentManagementSystem.sln
    secrets:
      snyk_token: ${{ secrets.SNYK_TOKEN }}
