name: Setup .NET

on:
  workflow_call:
    inputs:
      dotnet_version:
        required: false
        type: string
        default: '8.0'

jobs:
  setup-dotnet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ inputs.dotnet_version }}
