name: Snyk Security Scan

on:
  workflow_call:
    inputs:
      solution_path:
        required: true
        type: string
    secrets:
      snyk_token:
        required: true

jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'
      - name: Install Snyk
        run: npm install -g snyk
      - name: Restore
        run: dotnet restore ${{ inputs.solution_path }}
      - name: Snyk test
        run: snyk test --all-projects --project-type=dotnet --detection-depth=5 --sarif-file-output=snyk.sarif
        env:
          SNYK_TOKEN: ${{ secrets.snyk_token }}
        continue-on-error: true
      - name: Upload Snyk SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk.sarif
