name: User API CD

on:
  workflow_run:
    workflows: ["User API CI"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Docker login
        shell: bash
        run: |
          if [ -z "${{ secrets.DOCKER_USERNAME }}" ] || [ -z "${{ secrets.DOCKER_PASSWORD }}" ]; then
            echo "One or both Docker secrets are missing!"
            exit 1
          fi

          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Pull latest User API image
        run: docker pull gyliana/user-api:latest

      - name: Update Kubernetes deployment
        run: |
          kubectl set image deployment/user-api user-api=gyliana/user-api:latest
          kubectl rollout status deployment/user-api
