apiVersion: apps/v1
kind: Deployment
metadata:
  name: audit-sqlserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audit-sqlserver
  template:
    metadata:
      labels:
        app: audit-sqlserver
    spec:
      containers:
        - name: sqlserver
          image: mcr.microsoft.com/mssql/server:2022-latest
          ports:
            - containerPort: 1433
          env:
            - name: SA_PASSWORD
              value: "YourStrong!Password"
            - name: ACCEPT_EULA
              value: "Y"
---
apiVersion: v1
kind: Service
metadata:
  name: audit-sqlserver
spec:
  selector:
    app: audit-sqlserver
  ports:
    - port: 1433
      targetPort: 1433
